### PR TITLE
this patch makes it work with redis 6.0

### PR DESCRIPTION
**Pull request by xmcqueen**
see this issue: https://github.com/fcerbell/redismodule-smartcache/issues/1

### CODE REVIEW

**Comment by xmcqueen** [comment]
```
#show its version 6
redis-modules-docker]$ docker run -it --network some-network --rm redis redis-cli -h other-redis
other-redis:6379> help
redis-cli 6.0.10
To get help about Redis commands type:
      "help @<group>" to get a list of commands in <group>
.
.
.
other-redis:6379> 
#load the module and make the caches per the Vagrantfile
other-redis:6379> MODULE LOAD /scache.so
OK
other-redis:6379>  scache.create cache1 20 some-mysql 3306 redisdb redisuser redispassword
1) "cache1"
2) (integer) 20
3) "some-mysql"
4) (integer) 3306
5) "redisdb"
6) "redisuser"
7) "xxxxxxxx"
8) (integer) 139874267044368
other-redis:6379>  scache.create cache2 10 some-mysql 3306 redisdb redisuser redispassword
1) "cache2"
2) (integer) 10
3) "some-mysql"
4) (integer) 3306
5) "redisdb"
6) "redisuser"
7) "xxxxxxxx"
8) (integer) 139874267085088
other-redis:6379> scache.getvalue cache1 'select * from customer'
1) "1|Cerbelle|Franois|2017-05-26 00:00:00"
2) "2|Carbonnel|Georges|1970-01-01 00:00:00"
3) "3|Sanfilippo|Salvatore|1970-01-01 00:00:00"
other-redis:6379> scache.getvalue cache2 'select * from customer'
1) "1|Cerbelle|Franois|2017-05-26 00:00:00"
2) "2|Carbonnel|Georges|1970-01-01 00:00:00"
3) "3|Sanfilippo|Salvatore|1970-01-01 00:00:00"
other-redis:6379> ```

**Comment by HectorHumanes** [comment]
@xmcqueen can you please merge it? It would be very much appreciated

**Comment by xmcqueen** [comment]
I don't own this repo.  @fcerbell will have to merge it or else I can fork and merge.

**Review by fcerbell — APPROVED** [review]
Thanks

**Pull request merged**
